/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AccountProfileRouteImport } from './routes/account.profile'
import { Route as AccountWalletsRouteImport } from './routes/account.wallets'
import { Route as CheckoutIndexRouteImport } from './routes/checkout.index'
import { Route as NftNftIdRouteImport } from './routes/nft.$nftId'
import { Route as CheckoutConfirmationOrderIdRouteImport } from './routes/checkout.confirmation.$orderId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountProfileRoute = AccountProfileRouteImport.update({
  id: '/account/profile',
  path: '/account/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountWalletsRoute = AccountWalletsRouteImport.update({
  id: '/account/wallets',
  path: '/account/wallets',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutIndexRoute = CheckoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CheckoutRoute,
} as any)
const NftNftIdRoute = NftNftIdRouteImport.update({
  id: '/nft/$nftId',
  path: '/nft/$nftId',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutConfirmationOrderIdRoute =
  CheckoutConfirmationOrderIdRouteImport.update({
    id: '/confirmation/$orderId',
    path: '/confirmation/$orderId',
    getParentRoute: () => CheckoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/wallets': typeof AccountWalletsRoute
  '/nft/$nftId': typeof NftNftIdRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/checkout/confirmation/$orderId': typeof CheckoutConfirmationOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/wallets': typeof AccountWalletsRoute
  '/nft/$nftId': typeof NftNftIdRoute
  '/checkout': typeof CheckoutIndexRoute
  '/checkout/confirmation/$orderId': typeof CheckoutConfirmationOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/wallets': typeof AccountWalletsRoute
  '/nft/$nftId': typeof NftNftIdRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/checkout/confirmation/$orderId': typeof CheckoutConfirmationOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/signup'
    | '/account/profile'
    | '/account/wallets'
    | '/nft/$nftId'
    | '/checkout/'
    | '/checkout/confirmation/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/login'
    | '/signup'
    | '/account/profile'
    | '/account/wallets'
    | '/nft/$nftId'
    | '/checkout'
    | '/checkout/confirmation/$orderId'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/signup'
    | '/account/profile'
    | '/account/wallets'
    | '/nft/$nftId'
    | '/checkout/'
    | '/checkout/confirmation/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  AccountProfileRoute: typeof AccountProfileRoute
  AccountWalletsRoute: typeof AccountWalletsRoute
  NftNftIdRoute: typeof NftNftIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/profile': {
      id: '/account/profile'
      path: '/account/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AccountProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/wallets': {
      id: '/account/wallets'
      path: '/account/wallets'
      fullPath: '/account/wallets'
      preLoaderRoute: typeof AccountWalletsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/': {
      id: '/checkout/'
      path: '/'
      fullPath: '/checkout/'
      preLoaderRoute: typeof CheckoutIndexRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/nft/$nftId': {
      id: '/nft/$nftId'
      path: '/nft/$nftId'
      fullPath: '/nft/$nftId'
      preLoaderRoute: typeof NftNftIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/confirmation/$orderId': {
      id: '/checkout/confirmation/$orderId'
      path: '/confirmation/$orderId'
      fullPath: '/checkout/confirmation/$orderId'
      preLoaderRoute: typeof CheckoutConfirmationOrderIdRouteImport
      parentRoute: typeof CheckoutRoute
    }
  }
}

interface CheckoutRouteChildren {
  CheckoutIndexRoute: typeof CheckoutIndexRoute
  CheckoutConfirmationOrderIdRoute: typeof CheckoutConfirmationOrderIdRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutIndexRoute: CheckoutIndexRoute,
  CheckoutConfirmationOrderIdRoute: CheckoutConfirmationOrderIdRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  AccountProfileRoute: AccountProfileRoute,
  AccountWalletsRoute: AccountWalletsRoute,
  NftNftIdRoute: NftNftIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
